name: Build and deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Stop and run nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker rm nginx-server -f || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server -f || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server

            docker run --name nginx-server \
            --rm -d \
            --network="paskhin-me" \
            -p 443:443 -p 80:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-server
